### PR TITLE
Fix some todos.

### PR DESCRIPTION
**Pull request by calina-c**

### CODE REVIEW

**Comment by DMats** [comment]
@alexcos20 @calina-c In the download endpoint in provider, do we still need to validate that a transfer is not used for another service?

**Comment by alexcos20** [comment]
yes, the order event has a specific field, called serviceIndex.  Both should match

**Review by alexcos20 — APPROVED** [review]
We will make sure that services are a match in a new PR

**Comment by calina-c** [comment]
@David please handle the pending TODOs in a separate PR. Alex answered your question but this should become a separate issue.

**Pull request merged**
