### PR TITLE
Allow download only provider, without compute url.

### LINKED ISSUE #394: Provider fails to boot if there is no OPERATOR_URL defined
Screenshot 2022-03-14 at 16 19 03

Fixes:

- [ ] V3
- [ ] V4

If OPERATOR_URL is not defined, then provider should not expose any C2D endpoints

### LINKED ISSUE #395: C2D Environments filtered by chainID
When fetching the list of environments from C2D,  provider should also send chainID, so C2D could filter what environments are available for that provider

### PR DESCRIPTION
**Pull request by calina-c**
Closes #394. Closes #395.

### CODE REVIEW

**Comment by alexcos20** [comment]
can you remove changes from [provider_fees.py](https://github.com/oceanprotocol/provider/pull/399/files#diff-63b62246fbc8da10a0f1dfe53c633bada9fc1a20a65628433e7bcaa69d61fd57) ?

I will handle them in #402 , thanks

**Review by alexcos20 — CHANGES_REQUESTED** [review]
can you remove changes from [provider_fees.py](https://github.com/oceanprotocol/provider/pull/399/files#diff-63b62246fbc8da10a0f1dfe53c633bada9fc1a20a65628433e7bcaa69d61fd57) ?

I will handle them in #402 , thanks

**Comment by calina-c** [comment]
> can you remove changes from [provider_fees.py](https://github.com/oceanprotocol/provider/pull/399/files#diff-63b62246fbc8da10a0f1dfe53c633bada9fc1a20a65628433e7bcaa69d61fd57) ?
> 
> I will handle them in #402 , thanks

Yes, but I still need the one related to OPERATOR_SERVICE_URL, if that is fine with you.

**Comment by alexcos20** [comment]
yeah, sure

**Review by alexcos20 — APPROVED** [review]

**Pull request merged**
