### PR TITLE
Remove ocean.py dependency

### LINKED ISSUE #218: Remove ocean.py dependency

### PR DESCRIPTION
**Pull request by calina-c**
Closes #218

### CODE REVIEW

**Comment by DMats** [comment]
I'm working on adding unit tests to make the code climate coverage checks happy.

**Comment by calina-c** [comment]
> I'm working on adding unit tests to make the code climate coverage checks happy.

Since the code is mostly copied from ocean.py, where it is tested, code coverage is not top priority now. It's not a dramatic decrease anyway, and we can override CodeClimate. See: https://github.com/oceanprotocol/provider/issues/224

CC: @alexcos20 David fixed the docker build issue.

**Comment by DMats** [comment]
> ~~CC: @alexcos20 David fixed the docker build issue.~~ -> still failing due to dependencies

@calina-c can you clarify what you mean here? The docker image builds successfully on my machine.

**Comment by DMats** [comment]
> > ~CC: @alexcos20 David fixed the docker build issue.~ -> still failing due to dependencies
> 
> @calina-c can you clarify what you mean here? The docker image builds successfully on my machine.

@calina-c spoke to me via Slack.  She meant that we cannot approve this PR yet because the unit tests are still failing, not that the docker build was failing. 

I told her that once the unit tests were fixed, I'd rebuild the docker image, and rerun the ocean.js integration tests.

**Pull request merged**
